services:
  - type: web
    name: movie-stream
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn movie_stream.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-stream-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: TMDB_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: movie-stream-db
    databaseName: movie_stream
    plan: free