# Generated by Django 5.1.7 on 2025-03-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_profile_watchlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
